server:
  port: 9001
spring:
  application:
    name: taxi-fleet
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/taxi_fleet_db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
      minimum-idle: 2
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: ${RABBITMQ_HOST:user}
    port: 5672
    username: ${RABBITMQ_USER:user}
    password: ${RABBITMQ_PASSWORD:password}
