version: '3.8'
name: taxi-fleet
services:

  postgres:
    image: postgres:16.2
    container_name: postgresdb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taxi_fleet_db
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  taxi-fleet-ui:
    image: jnazarov/taxi-fleet-ui
    container_name: taxi-fleet-ui
    ports:
      - "3000:3000"

  taxi-fleet:
    image: jnazarov/taxi-fleet
    container_name: taxi-fleet
    depends_on:
      - postgresdb
    restart: always
    ports:
      - "9001:9001"
