version: '3.8'
name: taxi-fleet
services:

  postgres:
    image: postgres:16.2
    container_name: postgresdb
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=taxi_fleet_db
    ports:
      - "5432:5432"
    networks:
      - fleet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - fleet

  taxi-fleet-ui:
    image: jnazarov/taxi-fleet-ui
    container_name: taxi-fleet-ui
    ports:
      - "3000:3000"
    networks:
      - fleet

  taxi-fleet:
    image: jnazarov/taxi-fleet
    container_name: taxi-fleet
    depends_on:
      - postgres
      - rabbitmq
    restart: always
    environment:
      - RABBITMQ_HOST=fleet
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      - POSTGRES_URL=jdbc:postgresql://fleet:5432/taxi_fleet_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "9001:9001"
    networks:
      - fleet
networks:
  fleet:
    driver: bridge
